[alias]
t = "test --workspace"
c = "clippy --workspace --all-targets -- -D warnings"
check-all = "check --workspace --all-targets"
resq = "run -p resq-cli --"
perf = "run -p resq-perf --"
cleanup = "run -p resq-clean --"
bin = "run -p resq-bin --"
flame = "run -p resq-flame --"

[env]
CARGO_TERM_COLOR = "always"
RUST_BACKTRACE = "1"

[term]
progress.when = "always"
progress.width = 100
